CREATE TABLE IF NOT EXISTS ALERGIA(
    cpf VARCHAR(20),
    alergia VARCHAR(50),
    CONSTRAINT PK_ALERGIA PRIMARY KEY (cpf, alergia),
    CONSTRAINT FK_ALERGIA FOREIGN KEY (cpf) 
                REFERENCES CIDADAO
                ON DELETE CASCADE
);


INSERT INTO ALERGIA (cpf, alergia) VALUES ('1', 'TESTE1');
INSERT INTO ALERGIA (cpf, alergia) VALUES ('1', 'TESTE2');