CREATE TABLE IF NOT EXISTS ENFERMEIRO (
    cpf VARCHAR(11),
    coren VARCHAR(11),
    CONSTRAINT PK_ENFERMEIRO PRIMARY KEY(cpf),
    CONSTRAINT FK_ENFERMEIRO FOREIGN KEY(cpf)
                REFERENCES PROFISSIONAL(cpf)
                ON DELETE CASCADE,
    UNIQUE(coren)

);

-- Dados de exemplo
INSERT INTO ENFERMEIRO (cpf, coren) VALUES 
('44444444444', 'COREN123456'),
('55555555555', 'COREN789012');
