CREATE TABLE IF NOT EXISTS UNIDADE_BASICA_SAUDE(
    cnes VARCHAR(10),
    CONSTRAINT PK_UNIDADE_BASICA_SAUDE PRIMARY KEY (cnes),
    CONSTRAINT FK_UNIDADE_BASICA_SAUDE FOREIGN KEY (cnes)
                REFERENCES UNIDADE_SAUDE(cnes)
                ON DELETE CASCADE

);

-- Dados de exemplo
INSERT INTO UNIDADE_BASICA_SAUDE (cnes) VALUES 
('2000001'),
('2000002');

