CREATE TABLE IF NOT EXISTS HOSPITAL (
    cnes VARCHAR(10),
    capacidade INTEGER,
    CONSTRAINT PK_HOSPITAL PRIMARY KEY (cnes),
    CONSTRAINT FK_HOSPITAL FOREIGN KEY (cnes)
                REFERENCES UNIDADE_SAUDE(cnes)
                ON DELETE CASCADE
);

